image: python:3.7

before_script:
  - python --version
  - export http_proxy=http://wwwproxy.sandia.gov:80
  - export https_proxy=https://wwwproxy.sandia.gov:80
  - export no_proxy=.sandia.gov

stages:
  - Static Analysis
  - Test

syntax:
  stage: Static Analysis
  script:
    - ( unset https_proxy ; git fetch origin master )
    - if ! git diff --check origin/master HEAD ; then echo "See above whitespace errors." ; exit 1; fi
    - if find . -iname '*.py' -exec grep -l -P '\t' {} + ; then echo 'Above files have tabs.' ; exit 1 ; fi
    - pip install black && black --check .

pytest:
  stage: Test
  script:
    - pip install -e .[pygsti-integration,tests] && pytest
    - ( unset https_proxy ; cd .. && rm -fr qscout_gpf && git clone --depth 1 https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.sandia.gov/jaqal/qscout_gpf.git/  )
    - ( cd ../qscout_gpf && pip install -e . )
