image: python:3.7

before_script:
  - python --version
  - export http_proxy=http://wwwproxy.sandia.gov:80
  - export https_proxy=https://wwwproxy.sandia.gov:80
  - export no_proxy=.sandia.gov
  - pip install -r requirements.txt
  - pip install pytest

stages:
  - Test

pytest:
  stage: Test
  script:
    - pytest
