image: python:3.7

variables:
  TEST_REPRODUCE: $TEST_REPRODUCE
  QSCOUT_BRANCH: $QSCOUT_BRANCH
  JAQALPAQ_EXTRAS_BRANCH: $JAQALPAQ_EXTRAS_BRANCH

before_script:
  - python --version
  - if echo "$CI_PROJECT_URL" | grep -q cee-gitlab.sandia.gov ; then
        repo="https://nexus.web.sandia.gov/repository/pypi-proxy/simple" &&
        pip config set global.index "$repo" &&
        pip config set global.index-url "$repo" &&
        echo -e '[easy_install]\nindex_url = '"${repo}" >~/.pydistutils.cfg ;
        unset https_proxy ;
    fi
  - pip install --upgrade pip wheel

stages:
  - Analysis and Tests
  - Reproducibility

Unified Tests:
  stage: Analysis and Tests
  script:
    - git fetch origin master
    - if ! git diff --check origin/master HEAD ; then echo "See above whitespace errors." ; exit 1; fi
    - if find . -iname '*.py' -exec grep -l -P '\t' {} + ; then echo 'Above files have tabs.' ; exit 1 ; fi
    - devel/refresh-data-files setup.cfg.new
    - if ! diff -q setup.cfg.new setup.cfg ; then
        echo "Run devel/refresh-data-files to refresh examples list." ;
        exit 1 ;
      fi
    - pip install black~=22.1 && black --check .
    - cd ..
    - rm -fr qscout-gatemodels && git clone --depth 1 "$(echo "${CI_REPOSITORY_URL}" | sed 's/jaqalpaq.git/qscout-gatemodels.git/')" -b "${QSCOUT_BRANCH}"
    - LOCAL_JAQALPAQ=./jaqalpaq LOCAL_JAQALPAQ_EXTRAS="" LOCAL_QSCOUT_GATEMODELS=./qscout-gatemodels
      JAQALPAQ_OPTS="pygsti-integration,tests"
      ./jaqalpaq/install.sh
    - cd jaqalpaq
    - pytest

Notebooks:
  stage: Reproducibility
  only:
    variables:
      - $TEST_REPRODUCE == "1"
  script:
    - git fetch origin master
    - cd ..
    - rm -fr qscout-gatemodels && git clone --depth 1 "$(echo "${CI_REPOSITORY_URL}" | sed 's/jaqalpaq.git/qscout-gatemodels.git/')" -b "${QSCOUT_BRANCH}"
    - rm -fr jaqalpaq-extras && git clone --depth 1 "$(echo "${CI_REPOSITORY_URL}" | sed 's/jaqalpaq.git/jaqalpaq-extras.git/')" -b "${JAQALPAQ_EXTRAS_BRANCH}"
    - LOCAL_JAQALPAQ=./jaqalpaq LOCAL_JAQALPAQ_EXTRAS=./jaqalpaq-extras LOCAL_QSCOUT_GATEMODELS=./qscout-gatemodels
      JAQALPAQ_OPTS="pygsti-integration,notebooks" JAQALPAQ_EXTRAS_OPTS="qiskit,pyquil,cirq,projectq,pytket,tutorial"
      ./jaqalpaq/install.sh
    - pip install nbconvert ipykernel
    - ipython kernel install --user
    - cd jaqalpaq
    - find examples -name '*.ipynb' ! -name '*.nbconvert.ipynb' -exec devel/ipynb-execute {} --ExecutePreprocessor.kernel_name=python3 \;
    - find examples -name '*.nbconvert.ipynb' -print0 | xargs -0 tar -cf executed-notebooks.tar
    - find examples -name '*.ipynb' ! -name '*.nbconvert.ipynb' -print0 | (
        didfail=0 ;
        while IFS= read -r -d '' line ; do
          newf="${line%%.ipynb}.nbconvert.ipynb" ;
          if ! [ -f "$newf" ] ; then
            didfail=1 ;
            echo "${line} failed to build" ;
          elif ! devel/ipynb-diff "${line}" "${newf}" -q ; then
            didfail=1 ;
            echo "${line} changed" ;
          fi ;
        done ;
        exit "$didfail" ;
      )
  artifacts:
    when: always
    paths:
      - executed-notebooks.tar
    expire_in: 1 week
