image: python:3.7

before_script:
  - python --version
  - echo "$CI_PROJECT_URL" | grep -q cee-gitlab.sandia.gov && INDEX="-i https://nexus.web.sandia.gov/repository/pypi-proxy/simple"

stages:
  - Analysis and Tests

Unified Tests:
  stage: Analysis and Tests
  script:
    - ( unset https_proxy ; git fetch origin master )
    - if ! git diff --check origin/master HEAD ; then echo "See above whitespace errors." ; exit 1; fi
    - if find . -iname '*.py' -exec grep -l -P '\t' {} + ; then echo 'Above files have tabs.' ; exit 1 ; fi
    - pip install $INDEX setuptools_scm
    - pip install $INDEX black && black --check .
    - pip install $INDEX -e .[pygsti-integration,tests]
    - ( unset https_proxy ; cd .. && rm -fr qscout-gatemodels && git clone --depth 1 "$(echo "${CI_REPOSITORY_URL}" | sed 's/jaqalpaq.git/qscout-gatemodels.git/' )" )
    - ( cd ../qscout-gatemodels && pip install $INDEX -e . )
    - pytest
