image: python:3.7

before_script:
  - python --version
  - if echo "$CI_PROJECT_URL" | grep -q cee-gitlab.sandia.gov ; then
        repo="https://nexus.web.sandia.gov/repository/pypi-proxy/simple" &&
        pip config set global.index "$repo" &&
        pip config set global.index-url "$repo" &&
        echo -e '[easy_install]\nindex_url = '"${repo}" >~/.pydistutils.cfg ;
        unset https_proxy ;
    fi

stages:
  - Analysis and Tests

Unified Tests:
  stage: Analysis and Tests
  script:
    - git fetch origin master
    - if ! git diff --check origin/master HEAD ; then echo "See above whitespace errors." ; exit 1; fi
    - if find . -iname '*.py' -exec grep -l -P '\t' {} + ; then echo 'Above files have tabs.' ; exit 1 ; fi
    - devel/refresh-data-files setup.cfg.new
    - if ! diff -q setup.cfg.new setup.cfg ; then
        echo "Run devel/refresh-data-files to refresh examples list." ;
        exit 1 ;
      fi
    - pip install black && black --check .
    - cd ..
    - rm -fr qscout-gatemodels && git clone --depth 1 "$(echo "${CI_REPOSITORY_URL}" | sed 's/jaqalpaq.git/qscout-gatemodels.git/')"
    - ( cd jaqalpaq && pip install -e .[pygsti-integration,tests] )
    - ( cd qscout-gatemodels && pip install -e . )
    - cd jaqalpaq
    - pytest
