#!/bin/bash
set -e
if [ $# -lt 2 ] ; then
    echo "Two .ipynb's must be specified."
    exit 1
fi

A="$1"
B="$2"
shift 2

diff <("$(dirname "$0")/ipynb-purify" "$A") <("$(dirname "$0")/ipynb-purify" "$B") "$@"
