#!/bin/bash
set -e
purify() {
    <"$1" sed -e 's/"\(shell\.execute_reply\|iopub\.\(execute_input\|status\.\(busy\|idle\)\)\)": "[^"\]*"/"\1": "NOTIME"/' \
        -e 's/<\([^<>]* at 0x\)[0-9a-f]*>/\1NOADDRESS/'
}

if [ $# -lt 2 ] ; then
    echo "Two .ipynb's must be specified."
    exit 1
fi

A="$1"
B="$2"
shift 2

diff <(purify "$A") <(purify "$B") "$@"
